### ISSUE TITLE
(Group) Weapon System Picking UP

### ISSUE THREAD

**Issue by Migs** [niu-gdo/IGDO-Fall-2023-Project#11]
Create a class type for weapons (Alternatively, you can use scriptable objects)
- Allow for addition of different weapon types.

Create (or update) a script that will allow a character to pick up a weapon when they are within a certain distance.
- the weapon should be considered equipped
- the weapon on the map should be removed

Create (or update) a script that allows the player to drop a weapon they have.
- the weapon should be unequipped
- the weapon will then appear on the map

**Comment by Master449** [comment]
| Member | Mechanic |
|:---:|:---:|
| Adam | Class for Weapons |
| Fabian | Weapon Equipping |
| Toni | Drop Weapon |
| David | Drop Weapon |

**Comment by Master449** [comment]
*Placeholder for extra information that would not need to be in the main comment*

**Comment by ghost** [comment]
Created branch

**Comment by Master449** [comment]
I created a new branch because I can't be trusted with basic organization.

I created a drop button on the new main that includes James's stuff.

I made a few changes such as setting
- _weaponId default to 1
- OnDrop sets _weaponId to 0

Just need to figure out how to spawn the "weapon" with its _weaponId.

**Comment by ghost** [comment]
Flushed out pickup and drop systems.  and added weapon_pickup
